# Generated by Django 3.1.3 on 2021-05-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='data',
            field=models.TextField(),
        ),
    ]
