# Generated by Django 3.1.3 on 2021-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_lesson_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.TextField(default=None),
        ),
    ]
