# Generated by Django 3.1.3 on 2021-05-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210515_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='name_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lesson')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.DeleteModel(
            name='day',
        ),
    ]
