# Generated by Django 3.1.3 on 2021-05-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210516_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_group',
            name='link',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
