# Generated by Django 3.1.3 on 2021-05-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_name_group_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name_group',
            name='id_name',
        ),
    ]
