# Generated by Django 3.1.3 on 2021-05-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_name_group_id_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name_group',
            name='link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='groupid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.name_group', verbose_name='категория'),
        ),
    ]
