# Generated by Django 3.1.3 on 2021-05-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210516_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_group',
            name='group_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
