# Generated by Django 3.1.3 on 2021-05-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210516_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='categories',
        ),
        migrations.AddField(
            model_name='lesson',
            name='nameg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_group', to='mainapp.name_group'),
        ),
    ]
