# Generated by Django 3.1.3 on 2021-05-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210516_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='nameg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.name_group'),
        ),
        migrations.CreateModel(
            name='lesson_e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('group', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('lesson', models.TextField()),
                ('teacher', models.TextField()),
                ('day', models.CharField(max_length=25)),
                ('zam', models.PositiveIntegerField(default=1)),
                ('classroom', models.TextField(default=1)),
                ('nameg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.name_group')),
            ],
            options={
                'verbose_name': 'Еталон',
                'verbose_name_plural': 'Еталон',
            },
        ),
    ]
