# Generated by Django 3.1.3 on 2021-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_lesson_e_nameg'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_e',
            name='nameg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
