# Generated by Django 3.1.3 on 2021-05-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_lesson_e_nameg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='nameg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
